log:
  file: ../log/beidouxing.log
  debug: False
  format: "%(asctime)s--->>[%(filename)s--->line:%(lineno)d--%(levelname)s-->>%(message)s]"#带有特殊符号必须使用双引号


#测试报告配置
report_config:
  "file": "report.html" #测试报告名称
  "report_dir": "."     #测试报告路径
  "title": "自动化测试报告"  #测试报告标题
  "description": "北斗星自动化测试报告"  #测试报告描述
  "tester": "yantianpeng" #测试人
  "type_": "htr" #测试报告呢模版 htr表示html模版  br表示Beautifule模版


#项目路径
prject_dev_url:
  "url": "http://api.lemonban.com/futureloan"

#接口名称
interface:
  "register": "/member/register",  #注册接口
  "login": "/member/login",        #登录接口
  "recharge": "/member/recharge",  #充值接口
  "withdraw": "/member/withdraw",  #提现接口
  "updateNickname": "/member/update",  #更新昵称
  "getInfo": "/member/{member_id}/info",#获取单个用户信息
  "add_project": "/loan/add",  #新增项目
  "audit_project": "/loan/audit",  #审核项目
  "invest_project": "/member/invest" ,#投资项目
  "loans_list": "/loans"    #分页获取项目列表